// <auto-generated />
using System;
using Google_Keep.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Google_Keep.Migrations
{
    [DbContext(typeof(Google_KeepContext))]
    [Migration("20180803075155_InitialCreate123")]
    partial class InitialCreate123
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Google_Keep.Models.Checklist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Notesid");

                    b.Property<string>("checklist");

                    b.HasKey("id");

                    b.HasIndex("Notesid");

                    b.ToTable("Checklist");
                });

            modelBuilder.Entity("Google_Keep.Models.Label", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Notesid");

                    b.Property<string>("label");

                    b.HasKey("id");

                    b.HasIndex("Notesid");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("Google_Keep.Models.Note", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsPinned");

                    b.Property<string>("plain_text");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("Google_Keep.Models.Checklist", b =>
                {
                    b.HasOne("Google_Keep.Models.Note")
                        .WithMany("check")
                        .HasForeignKey("Notesid");
                });

            modelBuilder.Entity("Google_Keep.Models.Label", b =>
                {
                    b.HasOne("Google_Keep.Models.Note")
                        .WithMany("label")
                        .HasForeignKey("Notesid");
                });
#pragma warning restore 612, 618
        }
    }
}
